title:              Michael's Blog
email:              chengjuns@student.unimelb.edu.au
description:        A Blog Theme by Start Bootstrap
author:             CJentus16
baseurl:            ""
url:                "https://CJentus16.github.io"

# Social Profiles (stop it to see the changes)
twitter_username:   SBootstrap
github_username:    CJentus16
facebook_username:  Chengjun.shu
instagram_username:   
linkedin_username: chengjun-shu-8b4366258

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
